version: '2.1'

services:
  ccd-migration:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/spring-boot/template
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      - IDAM_CLIENT_ID
      - IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET
      - IDAM_API_URL
      - CCD_DATA_STORE_API_BASE_URL
      - DATA_STORE_IDAM_KEY
      - IDAM_S2S_URL
      - IDAM_USER
      - IDAM_PASS
      - MIGRATION_CASETYPE
      - MIGRATION_QUERY_SIZE
      - MIGRATION_CASE_LIMIT
    ports:
      - $SERVER_PORT:$SERVER_PORT
