core_case_data:
  api:
    url: ${CCD_DATA_STORE_API_BASE_URL:http://localhost:4452}

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  client:
    id: ${IDAM_CLIENT_ID:ccd_gateway}
    redirect_uri: http://localhost:3451/oauth2redirect
    scope: profile openid roles manage-user
    secret: ${IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET:ccd_gateway_secret}
  s2s-auth:
    microservice: ccd_data
    totp_secret: ${DATA_STORE_IDAM_KEY:AAAAAAAAAAAAAAAB}
    url: ${IDAM_S2S_URL:http://localhost:4502}

migration:
  caseIds:
  caseType: ${MIGRATION_CASETYPE}
  dryRun: false
  idam:
    password: ${IDAM_PASS}
    username: ${IDAM_USER}
  maxCasesToProcess: ${MIGRATION_CASE_LIMIT:50000}
  numThreads: 10
  elasticsearch:
    enabled: false
    querySize: ${MIGRATION_QUERY_SIZE:10000}

spring:
  application:
    name: ccd-case-migration-tool
logging:
  level:
    root: ERROR
    uk:
      gov:
        hmcts:
          reform: INFO
          reform.migration: ${log.level:INFO}
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
